FROM nginx:1.15

RUN apt-get update
RUN apt-get install -y zip

ADD ./ketos_gui.zip /
RUN unzip /ketos_gui.zip -d /
RUN cp -R /dist/* /usr/share/nginx/html

ADD ./nginx /etc/nginx/conf.d
ADD ./nginx/ketosbrain.nginx.conf /etc/nginx/nginx.conf
