version: '3.2'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.API.prod
    depends_on:
      - "db"
    ports:
      - "5000:5000"
    networks:
      - backend
    links:
      - db

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=mad
      - POSTGRES_PASSWORD=MAD
      - POSTGRES_DB=mad
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: ../dbdata
        target: /var/lib/postgresql/data
    networks:
      - backend

networks:
  backend: