FROM python:3

ADD maddevopsrsa /root/.ssh/

RUN mkdir -p /root/.ssh/
RUN chmod -R 600 /root/.ssh/
RUN ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
RUN chmod 600 ~/.ssh/maddevopsrsa
RUN git clone git@github.com:juliangruendner/mlService_DockerApi.git
    
CMD cd mlService_DockerApi && \
    git pull && \
    cd docker && \
    chmod +x ./start.sh && \
    ./start.sh