version: '3.2'

services:

  ml_service:
    container_name: ml_service
    build:
      context: .
      dockerfile: Dockerfile.mlService.dev
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - backend
      - environment
    links:
      - db
    volumes:
      - type: volume
        source: ../src
        target: /root/src
      - type: volume
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: /usr/bin/docker
        target: /usr/bin/docker
    env_file:
      - config_mlService.env

  db:
    container_name: db
    restart: unless-stopped
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - config_db.env
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: ../dbdata
        target: /var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
  environment: