import os

POSTGRES_USER = str(os.getenv('POSTGRES_USER', ''))
POSTGRES_PASSWORD = str(os.getenv('POSTGRES_PASSWORD', ''))
POSTGRES_DB = str(os.getenv('POSTGRES_DB', ''))

DOCKER_REGISTRY_USERNAME = str(os.getenv('DOCKER_REGISTRY_USERNAME', ''))
DOCKER_REGISTRY_PASSWORD = str(os.getenv('DOCKER_REGISTRY_PASSWORD', ''))
DOCKER_REGISTRY_URL = str(os.getenv('DOCKER_REGISTRY_URL', ''))
DOCKER_REGISTRY_DOMAIN = str(os.getenv('DOCKER_REGISTRY_DOMAIN', ''))